from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path

from ..core import FFmpegRunner
from ..models import OperationResult
from ..utils.paths import (
    ensure_input_exists,
    ensure_output_parent,
)


class Operation(ABC):
    """
    Base class for every FFmpeg operation.
    """

    @property
    @abstractmethod
    def output(self) -> str:
        """
        Output generated by this operation.
        """
        raise NotImplementedError

    @abstractmethod
    def build_args(self) -> list[str]:
        """
        Build FFmpeg arguments.
        """
        raise NotImplementedError

    def execute(
        self,
        runner: FFmpegRunner | None = None,
    ) -> OperationResult:

        runner = runner or FFmpegRunner()

        ensure_output_parent(self.output)

        result = runner.ffmpeg(
            self.build_args()
        )

        return OperationResult(
            operation_name=self.__class__.__name__,
            output=str(self.output),
            command=result.command,
            duration=result.duration,
            return_code=result.return_code,
        )

    @staticmethod
    def check_input(path: str | Path) -> Path:
        return ensure_input_exists(path)

    @staticmethod
    def check_output(path: str | Path) -> Path:
        return ensure_output_parent(path)